### ISSUE TITLE
get no .png file 

### ISSUE THREAD

**Issue by sunghyun-nam** [leofansq/Convert-ROS-bag-to-KITTI-format#12]
Hello

I used velodyne and zed camera and made rosbag file.

When I run './devel/lib/obstacle_detection/map_generate', I just only get .pcd files.

There were no Error message, so I don't know how to solve it.

The settings were as follows.

sub_lidar = nh.subscribe("/velodyne_points", 1000, &MapGenerationNode::lidarCallback, this);
ros::param::set("~image_transport", "compressed");
sub_camera = it.subscribe("/zedm/zed_node/rgb/image_rect_color", 1000, &MapGenerationNode::cameraCallback, this);

Thanks in advance.

**Comment by MAI-KOKO** [comment]
May I ask how you solved this problem?
