### ISSUE TITLE
Why does Pcd2Bin.cpp only read and write cloud->points[i].x&intensity?

### ISSUE THREAD

**Issue by hz3014** [leofansq/Convert-ROS-bag-to-KITTI-format#2]
On line 41 of the Pcd2Bin.cpp, It seems you are only reading the x and intensity values. What about y and z values?
bin_file.write((char*)&cloud->points[i].x,3*sizeof(float)); 
    bin_file.write((char*)&cloud->points[i].intensity,sizeof(float));

**Comment by leofansq** [comment]
> On line 41 of the Pcd2Bin.cpp, It seems you are only reading the x and intensity values. What about y and z values?
> bin_file.write((char*)&cloud->points[i].x,3_sizeof(float)); bin_file.write((char_)&cloud->points[i].intensity,sizeof(float));

bin_file.write((char*)&cloud->points[i].x,**3sizeof(float))**;  ---- >  x, y, z
